In [3]:
from nodes import *
import random

In [39]:
#random_gen inputs
branching_factor = (4, 8)
inputs = 8

In [68]:
import numpy as np

def generate_children(nodes, curr_node, scope, bf):
    curr_id = int(curr_node.id) + 1
    if isinstance(curr_node, PrdNode):
        num_children = random.randint(bf[0], bf[1])
        scopes = [[] for x in range(num_children)]
        weights = np.array([1.0]*num_children)/num_children
        print weights
        for s in scope:
            slot = np.random.choice(num_children, 1, p=weights)[0]
            val = weights[slot]/4
            weights += (weights[slot] - val)/(len(weights)-1)
            weights[slot] = val
            scopes[slot].append(s)
        scopes = filter(lambda x: x != [], scopes)
        print scopes
        for c in xrange(len(scopes)):
            if len(scopes[c]) == 1:
                a = random.random()
                child = Leaf(str(curr_id+1), a, 1-a, scopes[c][0])
                curr_id += 1
                nodes.append(child)
            else:
                child = SumNode(str(curr_id + 1))
                curr_node.children.append(curr_id + 1)
                nodes, curr_id = generate_children(nodes, child, scopes[c], bf)
        nodes.append(curr_node)
        return nodes, curr_id+1
    else:
        num_children = random.randint(bf[0], bf[1])
        scopes = [scope]*num_children
        print scopes
        for c in xrange(len(scopes)):
            child = PrdNode(str(curr_id + 1))
            curr_node.children.append(curr_id + 1)
            curr_node.weights.append(random.random() + 0.5)
            nodes, curr_id = generate_children(nodes, child, scopes[c], bf)
        nodes.append(curr_node)
        return nodes, curr_id+1
        

In [69]:
init_node = SumNode(0)

SPN, num_nodes = generate_children([], init_node, range(inputs), branching_factor)

[[0, 1, 2, 3, 4, 5, 6, 7], [0, 1, 2, 3, 4, 5, 6, 7], [0, 1, 2, 3, 4, 5, 6, 7], [0, 1, 2, 3, 4, 5, 6, 7], [0, 1, 2, 3, 4, 5, 6, 7], [0, 1, 2, 3, 4, 5, 6, 7], [0, 1, 2, 3, 4, 5, 6, 7]]
[ 0.16666667  0.16666667  0.16666667  0.16666667  0.16666667  0.16666667]
[[4], [3, 7], [0], [1, 5], [2, 6]]
[[3, 7], [3, 7], [3, 7], [3, 7], [3, 7], [3, 7], [3, 7]]
[ 0.125  0.125  0.125  0.125  0.125  0.125  0.125  0.125]
[[7], [3]]
[ 0.16666667  0.16666667  0.16666667  0.16666667  0.16666667  0.16666667]
[[3], [7]]
[ 0.25  0.25  0.25  0.25]
[[3], [7]]
[ 0.16666667  0.16666667  0.16666667  0.16666667  0.16666667  0.16666667]
[[3], [7]]
[ 0.14285714  0.14285714  0.14285714  0.14285714  0.14285714  0.14285714
  0.14285714]
[[7], [3]]
[ 0.2  0.2  0.2  0.2  0.2]
[[3], [7]]
[ 0.14285714  0.14285714  0.14285714  0.14285714  0.14285714  0.14285714
  0.14285714]
[[3], [7]]
[[1, 5], [1, 5], [1, 5], [1, 5]]
[ 0.125  0.125  0.125  0.125  0.125  0.125  0.125  0.125]
[[5], [1]]
[ 0.2  0.2  0.2  0.2  0.2]
[[1], [5]]
[

In [43]:
sum([ 0.18055556,  0.18055556,  0.18055556,  0.18055556,  0.18055556,  0.18055556])

1.08333336

In [49]:
sum([ 0.07142857,  0.15306122,  0.15306122 , 0.15306122 , 0.15306122,  0.15306122,
  0.15306122])

0.98979589

In [50]:
a = np.array([ 0.14285714,  0.14285714 , 0.14285714 , 0.14285714 , 0.14285714,  0.14285714,
  0.14285714])

In [51]:
s = 2

In [52]:
b = a[s]/2

In [53]:
b

0.071428569999999997

In [61]:
sum([ 0.11183333,  0.10183333,  0.05083333,  0.21183333 , 0.21183333  ,0.21183333])

0.89999998

In [71]:
len(SPN)

418

In [72]:
num_nodes

713